AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  square-connector

  SAM Template for square-connector

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SquareConnectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: square_connector/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - x86_64
      Environment:
        Variables:
          BM_KEY: '{{resolve:ssm:BM_KEY:1}}'
          SQUARE_KEY: '{{resolve:ssm:SQUARE_KEY:1}}'
      Events:
        SquareConnector:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /square
            Method: get
            Path: /square
            Method: POST
            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SquareConnectorApi:
    Description: "API Gateway endpoint URL for Prod stage for Square Connector function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/square/"
  SquareConnectorFunction:
    Description: "Square Connector Lambda Function ARN"
    Value: !GetAtt SquareConnectorFunction.Arn
  SquareConnectorFunctionIamRole:
    Description: "Implicit IAM Role created for Square Connector function"
    Value: !GetAtt SquareConnectorFunctionRole.Arn
